name: Check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '12', '10' ]
    name: Check - Node.js - ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Install dependencies
        run: yarn install #--immutable --immutable-cache --check-cache
      - name: Build target
        run: yarn build
      - name: Test code
        run: yarn test
      - name: DRY-RUN Release package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release --dry-run
